<?php include('../includes/functions.php');

$db = mysqli_connect('localhost', 'admin', '', 'songfarm-nov2015');
if(mysqli_connect_errno()) {
	die("Database connect failed: " .
			mysqli_connect_error() .
			" (" . mysqli_connect_errno() . ")"
	);
}

if($country_array = generate_ip_data()){
	// ip address generates a country code and country name
	list($country_code, $country_name, $city_name) = $country_array;
}

if(isset($_POST['register'])){
	var_dump($_POST);
}

?>
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Register</title>
	<script type="text/javascript" src="../public/js/jquery-1.11.3.min.js"></script>

	<style>
	div{
		border: 1px dotted black;
		width:50%;
		margin:1em auto;
		padding:0 2em 1em;
	}
	span#trigger-location{
		color:blue;
		cursor: pointer;
		text-decoration: underline;
		font-size: .9em;
	}
	li{
		display: inline-block;
		border: 1px dotted #aaa;
		padding:3px 6px;
		border-radius: 6px;
		margin:6px;
		cursor: pointer;
	}
	li:hover{
		background:#F64B99;
	}
	ul#result{
		border: 1px solid black;
		margin-top: -1px;
		width:18%;
		padding:0;
		position: relative;
		z-index: 12;
	}
	ul#result li{
		display: inline-block;
		width:100%;
		margin:0; padding:0;
		border: none;
	}
	</style>
</head>
<body>
	<h1>Registration form</h1>
	<a href="index_alt.php">Back</a>
	<form id="registration_form" action="" method="post">
		<!-- User type -->
		<div>
			<p>
				User Type
			</p>
			<input type="radio" name="user_type" value="1" data-type="artist">Artist
			<input type="radio" name="user_type" value="2" data-type="industry">Industry
			<input type="radio" name="user_type" value="3" data-type="fan">Fan
		</div>

		<!-- General Information -->
		<div>
			<p>
				Artist Name/Name
			</p>
			<input type="text" name="username" maxlength="60">
			<p data-type="comp_name"><!-- NOTE: displayed if user type 2 -->
				Company Name
			</p>
			<input type="text" name="comp_name" maxlength="60" data-type="comp_name">
			<p>
				Email
			</p>
			<input type="email" name="user_email" maxlength="60">
			<!-- NOTE: have fallbacks in place for browsers that don't support the email input (ie 8 & 9)-->
			<p>
				Password
			</p>
			<input type="password" name="user_password" maxlength="60">
			<p>
				Confirm password
			</p>
			<input type="password" name="conf_password" maxlength="60">
		</div>

		<div>
			<!-- get a list of artists to peruse from -->
			<p>
				As a songwriter, who are your biggest musical influences?
			</p>
			<input type="text" name="influence" value="" autocomplete="off">
			<ul id="result">
			</ul>
			<!-- user should have the option to pick from a list as well as type his/her unique preferences -->
			<!-- <input type="hidden" name="influences" autocomplete="off"> -->
		</div>

		<!-- Location -->
		<div>
			<?php if( (isset($city_name) && !empty($city_name)) && (isset($country_name) && !empty($country_name)) ) { ?>
			<p>We&apos;ve determined your location to be <b><?php echo $city_name.", ".$country_name ?></b> <span id="trigger-location">(Not right?)</span></p>
			<?php } else { ?>
			<p id="without-location">
				Please select your Country from the list below:
			</p>
			<?php } ?>
				<div id="user_location" style="display:none;">
				<!-- NOTE: is hidden unless triggered by span#trigger-location -->
					<?php include('../includes/countries_array.php'); ?>
					<select id="country_select">
						<!-- options are generated by ip search and country array -->
						<?php
						// if system can deduce from IP country name and code, then display it
						if(isset($country_name) && !empty($country_name)){ ?>
							<option value="<?php echo $country_code ?>"><?php echo $country_name; ?></option>
						<?php }

						// generate countries select menu
						$continents = [];
						// $countries comes from countries_array.php
						foreach ($countries as $country) {
							$continents[] = $country['continent'];
							$continents = array_unique($continents);
						}
						foreach($continents as $key => $continent){
							// excluding Asia, Africa, Antarctica
							if( $continent != 'Asia' && $continent != 'Africa' && $continent != 'Antarctica'){
								echo "<optgroup label=\"{$continent}\"></optgroup>";
								foreach ($countries as $key => $value) {
									if($value['continent'] == $continent){
										echo "<option value=\"$key\">". $value['country'] ."</option>";
									}
								}
							}

						}
						?>
					</select>
					<br>
					<input type="text" id="user_city" value="<?php if(isset($city_name) && !empty($city_name)){echo $city_name;} ?>" maxlength="40" placeholder="Type city name">
				</div>
			<p>
				Please select the most appropriate timezone for your location
			</p>
			<select name="timezone">
				<!-- options are generated based on the country and city -->
			</select>

			<!-- hidden inputs -->
			<input type="hidden" name="city_name" value="<?php if(isset($city_name)){echo $city_name;}?>">
			<input type="hidden" name="country_name" value="<?php if(isset($country_name)){echo $country_name;}?>">
			<input type="hidden" name="country_code" value="<?php if(isset($country_code)){echo $country_code;}?>">

		</div>

		<!-- <div>
			<ul id="genres">
				<?php
				// $sql = "SELECT * FROM genres";
				// if($result = mysqli_query($db, $sql)){
				// 	while($row = mysqli_fetch_array($result)){
				// 		echo "<li value=\"{$row['genre_id']}\">{$row['genre']}</li>";
				// 	}
				// }
				?>
			</ul>
		</div> -->

		<!-- Terms and Services -->
		<div>
			<input type="checkbox" name="terms_and_services" required>Terms and Services
		</div>

		<br><br>
		<input type="submit" name="register" value="submit">
	</form>
</body>
</html>
<script>
$(document).ready(function(){

	// company name input field
	var compName = $('form#registration_form p[data-type="comp_name"], input[data-type="comp_name"]').hide();
	// country select box container
	var countrySelectBoxContainer = $('div#user_location');
	// get country code that is generated in the hidden value of input name="country_code" by PHP
	var countryCode = $('form#registration_form input[name="country_code"]').val();
	// get city name that is generated in the hidden value of input name="city_name"
	var cityName = $('form#registration_form input[name="city_name"]').val();

	var ulInfluence = $('form#registration_form input[name="influence"]');


	// if user type is 2, then show company name field
	$('form#registration_form input[type="radio"]').on('click', function(){
		if($(this).val() == 2){
			compName.show();
		} else {
			compName.hide();
		}
	});


	// $('form#registration_form ul#genres li').on('click', function(){
	// 	var val = $(this).val();
	// 	$(this).css('background','#F64B99');
	// 	$('ul#genres').append('<input type="hidden" name="genres[]" value="'+val+'">');
	// });



	callAjax(countryCode);

	// if presence of country code, call Ajax to get timezones
	function callAjax(countryCode){
		if(countryCode.length >= 2){
			$.ajax({
				url : '../includes/timezonesFromCountryCode.php',
				data : {
					'country_code' : countryCode,
					'city_name' : cityName
				},
				method : 'POST',
				success: function(data){
					$('form#registration_form select[name="timezone"]').html(data);
				}
			})
		}
	}

	// if country select box changes (user chooses different country), clear out city input
	$('form#registration_form select#country_select').on('change', function(){
		var countryName = $(this).text();
		$('form#registration_form input[name="country_name"]').val(countryName);
		var countryCode = $(this).val();
		callAjax(countryCode);
		$('form#registration_form input[id="user_city"]').val('');
	})





	// if the span#trigger-location is clicked, display country select box
	$('form#registration_form span#trigger-location').on('click',function(){
		countrySelectBoxContainer.css('display','block')
	})

	// if certain p tag is present, display location select
	if($('#without-location').length){
		countrySelectBoxContainer.css('display','block');
	}

	// event trigger on key up of input field influences
	ulInfluence.on('keydown', function(){
		// get the value of this field
		var thisVal = $(this).val();
		// call api with this value
		callApi(thisVal);
	})

	function callApi(val){
		var APIkey = 'JY2IF4KCSFWEUAZCJ';
		var target = $('form#registration_form input[name="influence"] + ul');
		$.ajax({
			url: 'http://developer.echonest.com/api/v4/artist/search?api_key='+APIkey+'&name='+val+'&bucket=familiarity&results=5&format=jsonp',
			method: 'GET',
			dataType:'jsonp',
			// cache:true,
			success: function(object){
				target.children().remove();

				var obj = object['response']['artists'];
				var artist = [];

				$.each(obj, function(key, value){
					var rank = value['familiarity'];
					if(rank >= 0.35){
						artist.push(value['name']);
						artist = jQuery.unique(artist);
						target.append('<li class="item">'+artist+'</li>');
					}
				});
			}
		}); // end of ajax
	}

	// this bit gets the text value of li.item in the ul
	$('ul#result').on('click','.item',function(){
		var value = $(this).text();
		$('input[name="influence"]').val(value);
		// console.log(value);
	})

	// key detection for arrow keys
	$(document).keydown(function(e) {
    switch(e.which) {
        case 37: // left
        break;

        case 38: // up
				// code goes here
        break;

        case 39: // right
        break;

        case 40: // down
				// code goes here
        break;

        default: return; // exit this handler for other keys
    }
    e.preventDefault(); // prevent the default action (scroll / move caret)
});
}); // doc ready


</script>
