<?php require_once("../includes/initialize.php");
/**
* References 'functions.php' generate_ip_data() function
*/
if( $location_by_ip = generate_ip_data() ){ // if ip array comes back
	// array containing expected value generated by generate_ip_data()
	$expected = array('country_code','country_name','city_name','continent_code');

	while ( list($key, $value) = each($location_by_ip) ) {
		if( in_array($key, $expected) ){
			// assign variable variables
			${$key} = $value;
		}
	}

} // end of: if( $location_by_ip = generate_ip_data() )
?>
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Songcircle - Virtual Songwriter's Circle</title>
        <meta name="description" content="Share your newest song in a live virtual songwriter's circle">
        <!-- a meta "description" can and should be included on each independent page to DESCRIBE it -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <meta property="og:url" content="http://www.songfarm.ca/songcircle.php">
        <meta property="og:title" content="Songcircle - Virtual Songwriter's Circle">
        <meta property="og:description" content="Participate in a virtual songwriter's circle and workshop your songs with other songwriters - all from the comfort of your home. Register Today!">
        <meta property="og:image" content="http://www.songfarm.ca/images/songfarm_logo_l.png">
        <meta property="og:image:width" content="1772">
        <meta property="og:image:height" content="1170">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="stylesheet" href="css/index.css">
        <link rel="stylesheet" href="css/songcircle.css">
        <script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>
        <!-- <script type="text/javascript" src="//platform.linkedin.com/in.js">
            api_key:   77fxwmu499ca9c
            authorize: true
        </script> -->
        <!--[if lt IE 9]>
          <script src="js/html5-shiv/html5shiv.min.js"></script>
          <script src="js/html5-shiv/html5shiv-printshiv.min.js"></script>
          <script src="js/respond.js" type="text/javascript"></script>
          <script src="//ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
        <![end if]-->
    </head>
		<body>
      <?php include("../includes/layout/header.php") ?>
      <section>

        <article id="main"><!-- holds background image -->
          <!-- Introduction to Songcircle -->
          <h1 id="headline">
            <span class="bold">Real songs. Real songwriters. Real-time.</span>
          </h1>
					<hgroup>
						<h2 id="byline">
							Play your song live in a virtual Songwriters' Circle. Get real-time feedback, collaborate on ideas, and hone your craft.
	          </h2>
						<h2><b>
						Register for a Songcircle today!
						</b></h2>
					</hgroup>
        </article>

        <article id="schedule">

          <h3>Upcoming Songcircles:</h3>

					<!-- Schedule of Songcircles -->
          <?php
          // $songcircle->open_songcircle_exists();
          echo $songcircle->display_songcircles();
          ?>

        </article>

        <article id="aboutSongcircle">
          <h3>What is a Songcircle?</h3>
          <p>
            A <a href="#linkToBlog" style="color:blue; text-decoration:underline;">Songcircle</a> is an <em>opportunity</em> for Songwriters to gather together, share their ideas, play their songs and get real-time feedback from other artists from around the world.
          </p>
					<p>Conducted over the internet in real-time, Songcircles are free to virtually anyone with an internet connection, a webcam, and a song</p>
					<p>
						What traditionally had to be done in a brick and mortar establishment is now being pioneered by Songfarm as a way to offer songwriters the opportunity to nurture their craft and grow their network - all without having to leave the house.
					</p>
					<p>
						Experience one for yourself today! <a href="songcircle.php#headline" style="color:blue; text-decoration:underline;">Register for a Songcircle today!</a>
					</p>

        </article>

      </section>

			<!-- Use RDFa to define songcircle events // schema.org -->
			<!-- remember to use the '<time></time>' attribute when scheduling songcircles-->

      <?php include("../includes/layout/footer.php") ?>

			<!-- Registration Form -->

      <div id="overlay"></div>
      <form id="registration_form" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

    		<!-- General Information -->
    		<div id="details">

					<h4>Songcircle Registration</h4>

    			<input type="text" name="username" maxlength="60" placeholder="Please enter your Name" tabindex="1">
					<div class="form_error" name="username"></div>

    			<input type="email" name="user_email" maxlength="80" placeholder="Please enter your Email" tabindex="2">
    			<!-- NOTE: have fallbacks in place for browsers that don't support the email input (ie 8 & 9)-->
					<div class="form_error" name="user_email"></div>

    		</div>

    		<!-- Location -->
    		<div id="loc">

				<!-- conditional depending of whether or not generate_ip_data() has provided values -->
				<?php
					if((isset($country_code) && !empty($country_code))
					&& (isset($country_name) && !empty($country_name))){
				?>
					<p id="timezone">
						Please select the most appropriate timezone for your location
					</p>

					<!-- Jquery inserts timezone select list here if user has IP data -->

					<p id="locationMsg">
						Timezone based on <b><?php echo $country_name; ?></b>
						<br>
						<span id="trigger-location" tabindex="4">&lpar;Not right?&rpar;</span>
					</p>

				<?php
					} else {
				?>
				<!-- if not values have been generated from generate_ip_data() -->
					<p>
						Please select your country from the list
					</p>
				<?php
					}
				?>
					<div id="user_location" class="hide">

						<!-- include array of countries -->
						<?php include('../includes/countries_array.php'); ?>

  					<select id="country_select" tabindex="5">
						<?php
							if((isset($country_name) && !empty($country_name))
							&& (isset($country_code) && !empty($country_code))){
						?>
							<option value="<?php echo $country_code ?>"><?php echo $country_name; ?></option>
						<?php
							} // end of: (isset($country_name)) && (isset($country_code))

						// init $continents array
						$continents = [];

						// NOTE: $countries array is contained in include('../includes/countries_array.php')
						foreach ($countries as $country) {
							// populate $continents array with continents countries array
							$continents[] = $country['continent'];
							// remove duplicate values with array_unique
							$continents = array_unique($continents);
						}

						foreach($continents as $key => $continent){
							// if NOT continent == Asia, Africa, Antarctica..
							if( $continent != 'Asia' && $continent != 'Africa' && $continent != 'Antarctica'){
								echo "<optgroup label=\"{$continent}\"></optgroup>";
								foreach ($countries as $key => $value) {
									if($value['continent'] == $continent){
										echo "<option value=\"$key\">". $value['country'] ."</option>";
									}
								}
							}
						}
						?>
  					</select>

  				</div>

    		</div>
				<!-- end of: Location -->

				<!-- hidden inputs for location -->
				<input type="hidden" name="fullTimezone" value="">
				<input type="hidden" name="city_name" value="<?php if(isset($city_name)){echo $city_name;}?>">
				<input type="hidden" name="country_name" value="<?php if(isset($country_name)){echo $country_name;}?>">
				<input type="hidden" name="country_code" value="<?php if(isset($country_code)){echo $country_code;}?>">

				<!-- Code of Conduct -->
				<div>
					<div id="codeOfConduct">
						<input class="double" type="checkbox" name="codeOfConduct" tabindex="6">&nbsp;I have read and agree to adhere to the <a href="#" style="text-decoration:underline" tabindex="7">Code&nbsp;of&nbsp;Conduct</a>
					</div>
					<!-- Form submit -->
					<input type="submit" name="register" value="Register" tabindex="8">
				</div>

				<!-- error output -->
				<div id="output"></div>

    	</form>

		</body>

    <script type="text/javascript" src="js/social.js"></script>
    <script>
		$(document).ready(function(){

			// Where re-direction will go after successful registration:

			/* local site */
			var redirectURL = 'http://localhost/songfarm-oct2015/public/index.php';

			/* live test site */
			// var redirectURL = 'http://test.songfarm.ca/public/';

			// Register button from Songcircle Table
			var btnRegister = $('input[data-id="triggerRegForm"]');
			// Waiting list button from Songcircle Table
			var btnWaitList = $('input[data-id="triggerWaitList"]');
			// Registration Form
			var registrationForm = $('#registration_form');
			// Registration Form Submit Button
			var formSubmit = $('#registration_form input[type="submit"]');
			// registration form submit button
			var formSubmit = $('form#registration_form input[type="submit"]');
			// Overlay for Registration Form
			var overlay = $('#overlay');


			/* IP Generated Data (functions.php) */
			// city name hidden input value on load
			var cityName = $('form#registration_form input[name="city_name"]').val();
			// country code hidden input value on load
			var countryCode = $('form#registration_form input[name="country_code"]').val();
			// country name hidden input value on load
			var countryName = $('form#registration_form input[name="country_name"]').val();
			// dyamically inputted:
			// full timezone hidden input value once selected
			var fullTimezoneVal = $(registrationForm).find('input[name="fullTimezone"]');

			/* Element variables */
			// username input field
			var usernameInput = $('#registration_form input[name="username"]');
			// email input
			var emailInput			= $('#registration_form input[name="user_email"]');
			// timezone select field dropdown
			var selectFullTimezone = $('form#registration_form select[name="timezone"]');
			// container for country select field
			var countrySelectBoxContainer = $('div#user_location');
			// country select trigger
			var countryTrigger = $('form#registration_form span#trigger-location');
			// country select field dropdown
			var countrySelectDropdown = $('form#registration_form select#country_select');

			/* IP sensitive variables */
			var timezoneText = '<p>Please select your timezone</p>';
			var timezoneSlctField = '<select name="timezone" tabindex="3"></select>';
			var formHasIP = $('p#timezone');

			// error output div
			var outputDiv = $('#registration_form div#output');

			/* Confirmation notification container (after submission of registration form) */
			var confirmContainer = $(document.createElement('div')).attr('id','modal').addClass('modalClass');
			$('body').prepend(confirmContainer);

			// create array
			var songcircleData = [];
			var otherArray = [];

			/* Validation measures */
			var nameIsValid 			= false;
			var emailIsValid 			= false;
			var codeOfConductRead = false;
			var timezoneValid 		= false;

			/* Code of Conduct */
			var codeOfConductDiv = $('#registration_form div#codeOfConduct');
			var codeOfConductCheckbox = $('#registration_form div#codeOfConduct input[name="codeOfConduct"]');

			// error spans
			var usernameError		= $('div.form_error[name="username"]');
			var emailError			= $('div.form_error[name="user_email"]');
			// timezone error
			$('#registration_form div#loc').append('<div class="form_error" name="timezone"></div>');
			var timezoneError = $('div.form_error[name="timezone"]');

			// Code of Conduct error counter
			// Used to alert the user if they have forgotten to confirm Code of Conduct
			var cOcErrorCounter = 0;

			// email regex
			var myRegex = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
			var emailRegEx = new RegExp(myRegex);


			/**
			* When user clicks on the 'Register' button on songcircle.php
			* open the registration form
			*/
			$(btnRegister).add(btnWaitList).on('click', function(e){
				e.preventDefault();
				overlay.show();
				registrationForm.show();
				// call function to retrieve songcircle data by ROW number
				getAndSetSongcircleDataByRow($(this).data('row'));
				usernameInput.focus();
			});

			/**
			* Gathers input data for a given row and
			* Sets it into the registration form
			*
			*	Created: 01/28/2016
			*
			* @param (int) a row number
			*/
			function getAndSetSongcircleDataByRow(rowNumber){

				// child inputs of songcircle data row
				var childInputs = $('#songcircleTable tr[data-row="'+rowNumber+'"]').find('td.form').children('[type="hidden"]');

				// loop through the child elements and extract key/value pairs
				$(childInputs).each(function(index, element){
					var name 	= $(element).attr('name');
					var str = '<input type="hidden" name="'+name+'" value="'+$(element).val()+'">';
					$(formSubmit).before(str);
				});

			}

			/**
			*	Targets specific hidden inputs in the registration form
			* and Removes them
			*/
			function removeSongcircleData(){
				var submitBtnParent = $(formSubmit).parent().find('input[type="hidden"]').remove();
			}

			/**
			*	Find the selected option of timezone select field
			* assign value to fullTimezone hidden field
			*/
			function getSetFullTimezone(){
				fullTimezone = $(registrationForm).find('select[name="timezone"] option:selected').html();
				fullTimezoneVal.val(fullTimezone);
			}

			callAjax(countryCode);

			/**
			*	Takes IP generated data (country code) ,
			* and returns country-specific timezone data
			*
			* @param (string) a two letter country code
			* @param (string) a city name
			* @return string formatted timezones (1 or more)
			*/
			function callAjax(countryCode){
				if(countryCode.length >= 2){
					$.ajax({
						url : '../includes/timezonesFromCountryCode.php',
						data : {
							'country_code' : countryCode,
							'city_name' : cityName
						},
						method : 'POST',
						success: function(data){
							$('form#registration_form select[name="timezone"]').html(data);
						}
					});
				}
			} // end of: callAjax(countryCode)

			/**
			* Click event for manual country select by user
			*/
			$(countryTrigger).on('click', function(){
				$(this).hide();
				$('p#locationMsg').text('Please select your country');
				countrySelectBoxContainer.css('display','block');
				countrySelectDropdown.focus();
			});

			/**
			*	When user changes the country select box
			*/
			$(countrySelectDropdown).on('change', function(){

				// get value of selected option
				var countryNameVal = $(this).find('option:selected').text();
				// insert value into country name hidden input field
				$('form#registration_form input[name="country_name"]').val(countryNameVal);
				// get value of selected option
				var countryCodeVal = $(this).val();
				// insert value into country code hidden input field
				$('form#registration_form input[name="country_code"]').val(countryCodeVal);
				// clear value of hidden field
				$('form#registration_form input[name="city_name"]').val('');

				callAjax(countryCodeVal);

			});

			/**
			* Variable Location Form Fields
			*/
			// if presence of IP address elements
			if( formHasIP.length ){
				$('p#timezone').after(timezoneSlctField);
			} else {
				// if no presence of IP address elements
				// show country selection container
				countrySelectBoxContainer.show();
				// insert elements after selection container
				countrySelectBoxContainer.after(timezoneText+timezoneSlctField);
			}

			/**
			*	Closes registration form, hide overlay
			* when user clicks outside of the form
			*/
			$(overlay).on('click', function(){
				$(this).hide();
				registrationForm.hide();
				// hide confirmation notice, if present
				confirmContainer.hide();
				// hide Code of Conduct, if present
				codeOfConContainer.hide();

				removeSongcircleData();
			});

			/**
			* On Songcircle Registration form submission
			*/
			formSubmit.on('click', function(evt){
				/**
				* Write function for correct outlining of true or false validations
				*/
				// remove the hidden input containing city name so that it doesn't submit with the form
					$('input[name="city_name"]').remove();

				// call function to retrieve full timezone
					getSetFullTimezone();

				// hide any possible error spans from previous submissions
					usernameError.hide();
					emailError.hide();
					timezoneError.hide();

				/* Input validations */
					/* Username */
					if( !usernameInput.val() ){	// if username input field empty
						usernameInput.css('outline','3px solid red').focus();
						// flag to signal there was an error with the username
						var username_flag = true;
					}
					// if username is too short
					else if ( usernameInput.val().length <= 1 ){
						// focus on username input
						$(usernameInput).focus();
						// show error message
						usernameError.html('Username too short!').show();
						// flag to signal there was an error with the username length
						var username_length_flag = true;
					}	else { // no errors with username
						// hide any error spans
						$(usernameError).hide();
						// Outline goes green -- function used here
						usernameInput.css('outline','3px solid green');
						// validate measure
						nameIsValid = true;
					}

					/* Email */
					if( !emailInput.val() ){ // if email input field empty
						emailInput.css('outline','3px solid red');
						// if NOT username error, focus on email field
						if(!username_flag && !username_length_flag){
							emailInput.focus();
						}
					}
					// if not not valid email
					else if( !emailRegEx.test( emailInput.val() ) ){
						emailInput.css('outline','3px solid red').focus().select();
						emailError.html('Please enter a valid email address.').show();
					}	else {
						// hide any error spans
						$(emailError).hide();
						// change outline to green
						emailInput.css('outline','3px solid green');
						// validate measure
						emailIsValid = true;
					}

					/* Timezone validation */
					if( !fullTimezoneVal.val() ){
						timezoneError.html('Please select your timezone').show();
					} else {
						// console.log('no timezone error.. Validating true');
						timezoneValid = true;
					}

					// if code of conduct button is not checked

					if( !codeOfConductCheckbox.prop('checked') ){
						cOcErrorCounter++;
						console.log('error counter: '+cOcErrorCounter);

						// construct error message
						var alertMsg = '<div id="cOcAlertBox">';
								alertMsg += '<p>Please acknowledge that you have read and understand the <a href="#">Songfarm Code of Conduct</a></p>'
								alertMsg += '</div>';
						// append message to div
						codeOfConductDiv.append(alertMsg);
						if(cOcErrorCounter >= 3){
							// codeOfConductDiv.effect('shake');
							console.log('shake the box');
							/*
								program a shaking effect to occur on the error alert box
							*/
						}
					} else {
						// validate measure
						codeOfConductRead = true;
					}

				// test that all validation conditions are met
				if( nameIsValid && emailIsValid && timezoneValid && codeOfConductRead ){
					// no errors

					// serialize form data
					var formData = registrationForm.serialize();

					// send data to validation (includes/registerSongcircle.php)
					$.ajax({
						url : '../includes/songcircleRegisterUser.php',
						data : {
							'formData' : formData
						},
						method : 'POST',
						success: function(data){
							// hide form and overlay
							registrationForm.hide();
							overlay.hide();

							try {	// try to parse return data in JSON format

							var songcircleObj = $.parseJSON(data); // parse return messages
							var notificationMsg;

							// if returned data contains waitlist flag
							if(songcircleObj.waitlist == true){
								// waitlist message
								notificationMsg = "<p><span>Thanks, "+songcircleObj.username+"!</span></p>";
								notificationMsg+= "<p>You've been added to the Waiting List for <b>"+songcircleObj.eventTitle+"</b> on <b>"+songcircleObj.date_time+"</b></p>";
								notificationMsg+= "<p>We'll notify as soon as a spot opens up!</p>"
							} else {
								// registration message
								notificationMsg = "<p><span>Thank You, "+songcircleObj.username+"!</span></p>";
								notificationMsg+= "<p>Please go your email and confirm your attendance to <b>"+songcircleObj.eventTitle+"</b> plus receive some simple tips on getting the most out of this upcoming Songcircle.</p>";
							}

								// wait 5 seconds then redirect
								setTimeout(function(){
									window.location.replace(redirectURL);
								}, 5000);

							} catch(e) { // catch returned error message as 'data'

								var notificationMsg = data;

								// trim returned data for keywords ('name','email')
								var newStr = notificationMsg.substring( notificationMsg.indexOf('=')+2, notificationMsg.indexOf("_") );

								switch (newStr) {
									case 'name':
										var nameFocus = true;
										break;
									case 'email':
										var emailFocus = true;
										break;
									// default:
									// 	console.log('End of Switch Statement');
								}
								if(nameFocus || emailFocus){
									// set timeout to return to form
									setTimeout(function(){
										overlay.show();
										registrationForm.show();
										if(nameFocus){
											usernameInput.focus();
										} else if (emailFocus) {
											emailInput.focus().select();
										}
										// hide notification box
										confirmContainer.hide();
									}, 2500);
								}
								else
								{
									setTimeout(function(){
										console.log('mailing error occurred');
										overlay.show();
										registrationForm.show();
										confirmContainer.hide();
									}, 7500);
								}
							} finally {
								// remove any child elements, if existing
								$(confirmContainer).empty();
								// append notification message to container
								$(confirmContainer).append(notificationMsg);
								// show overlay & confirmation container
								overlay.show();
								confirmContainer.show();
							}
						} // end of: success: function(data)
					}); // end of: $.ajax
				} // end of: if( nameIsValid && emailIsValid && timezoneValid && codeOfConductRead )
			 	else
				{
					console.log('registration failed due to validation error..');
					// exit script
					return false;
				}
				return false;
			}); // end of on formSubmit

			/**
			*	Hide Code of Conduct error alert box if checked
			*/
			codeOfConductCheckbox.change(function(){
				if( $(this).is(':checked') ){
					if( $('div#cOcAlertBox').length ){
						$('div#cOcAlertBox').hide();
					}
				}
			});


			/**
			* If there are no registered user, display a unique message
			*	Otherwise display registered users
			*/
			// Trigger for showing songcircle participants
			var triggerDiv = $('span.triggerParticipantsTable');
			var participantsTable = $('.participantsTable');

			triggerDiv.on('mouseover mouseout', function(){
				$(this).next().toggle();
			});


			/* Code of Conduct Modal*/

			/* CSS for Code Of Conduct Modal */
			var modalTrigger = $('#codeOfConduct a');
			var codeOfConContainer = $('<div id="cOcModal"></div>');

			/**
			* Function for retrieving 'Songfarm Code of Conduct' from filesystem
			*/
			$.fn.getCodeOfConduct = function(){
				$.get('../codeOfConduct.html', function(data){
					// construct modal
					codeOfConContainer.html(data);
					// append modal container at end of body
					$('body').append(codeOfConContainer);
					// show modal
					codeOfConContainer.show();
				});
			}

			// on trigger click
			modalTrigger.on('click', function(){
				// get page
				$(this).getCodeOfConduct();
			});

			/**
			* Open Modal event for Code of Conduct error alert
			*/
			$('body').on('click', '#cOcAlertBox', function(){
				$.fn.getCodeOfConduct();
			});

			/**
			* Event: User agrees with Code of Conduct
			*/
			$('body').on('click', 'button.cOcAgree', function(){
				// check checkbox if agree
				codeOfConductCheckbox.prop('checked', true);
				// hide Code of Conduct container
				codeOfConContainer.fadeOut().hide();
			});

			/**
			* Event: User does not agree with Code of Conduct
			*/
			$('body').on('click', 'a[name="cOcNotAgree"]', function(){
				codeOfConContainer.fadeOut().hide();
			});

		}); // end document.ready

	</script>
</html>
